/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AcademicRouteImport } from './routes/academic'
import { Route as AmuletsRouteImport } from './routes/amulets'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DivinationRouteImport } from './routes/divination'
import { Route as MentorshipRouteImport } from './routes/mentorship'
import { Route as WorkWithMeRouteImport } from './routes/work-with-me'
import { Route as WritingRouteImport } from './routes/writing'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicRoute = AcademicRouteImport.update({
  id: '/academic',
  path: '/academic',
  getParentRoute: () => rootRouteImport,
} as any)
const AmuletsRoute = AmuletsRouteImport.update({
  id: '/amulets',
  path: '/amulets',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DivinationRoute = DivinationRouteImport.update({
  id: '/divination',
  path: '/divination',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorshipRoute = MentorshipRouteImport.update({
  id: '/mentorship',
  path: '/mentorship',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkWithMeRoute = WorkWithMeRouteImport.update({
  id: '/work-with-me',
  path: '/work-with-me',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingRoute = WritingRouteImport.update({
  id: '/writing',
  path: '/writing',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academic': typeof AcademicRoute
  '/amulets': typeof AmuletsRoute
  '/contact': typeof ContactRoute
  '/divination': typeof DivinationRoute
  '/mentorship': typeof MentorshipRoute
  '/work-with-me': typeof WorkWithMeRoute
  '/writing': typeof WritingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academic': typeof AcademicRoute
  '/amulets': typeof AmuletsRoute
  '/contact': typeof ContactRoute
  '/divination': typeof DivinationRoute
  '/mentorship': typeof MentorshipRoute
  '/work-with-me': typeof WorkWithMeRoute
  '/writing': typeof WritingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academic': typeof AcademicRoute
  '/amulets': typeof AmuletsRoute
  '/contact': typeof ContactRoute
  '/divination': typeof DivinationRoute
  '/mentorship': typeof MentorshipRoute
  '/work-with-me': typeof WorkWithMeRoute
  '/writing': typeof WritingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/academic'
    | '/amulets'
    | '/contact'
    | '/divination'
    | '/mentorship'
    | '/work-with-me'
    | '/writing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/academic'
    | '/amulets'
    | '/contact'
    | '/divination'
    | '/mentorship'
    | '/work-with-me'
    | '/writing'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/academic'
    | '/amulets'
    | '/contact'
    | '/divination'
    | '/mentorship'
    | '/work-with-me'
    | '/writing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcademicRoute: typeof AcademicRoute
  AmuletsRoute: typeof AmuletsRoute
  ContactRoute: typeof ContactRoute
  DivinationRoute: typeof DivinationRoute
  MentorshipRoute: typeof MentorshipRoute
  WorkWithMeRoute: typeof WorkWithMeRoute
  WritingRoute: typeof WritingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic': {
      id: '/academic'
      path: '/academic'
      fullPath: '/academic'
      preLoaderRoute: typeof AcademicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amulets': {
      id: '/amulets'
      path: '/amulets'
      fullPath: '/amulets'
      preLoaderRoute: typeof AmuletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/divination': {
      id: '/divination'
      path: '/divination'
      fullPath: '/divination'
      preLoaderRoute: typeof DivinationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentorship': {
      id: '/mentorship'
      path: '/mentorship'
      fullPath: '/mentorship'
      preLoaderRoute: typeof MentorshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work-with-me': {
      id: '/work-with-me'
      path: '/work-with-me'
      fullPath: '/work-with-me'
      preLoaderRoute: typeof WorkWithMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writing': {
      id: '/writing'
      path: '/writing'
      fullPath: '/writing'
      preLoaderRoute: typeof WritingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcademicRoute: AcademicRoute,
  AmuletsRoute: AmuletsRoute,
  ContactRoute: ContactRoute,
  DivinationRoute: DivinationRoute,
  MentorshipRoute: MentorshipRoute,
  WorkWithMeRoute: WorkWithMeRoute,
  WritingRoute: WritingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
